class FixCapabilityContract {
    static getCapabilities() {
        return {
            ok: true,
            version: "46.0",
            source: "SERVICE_MIRROR",
            engine_registry_compatibility: "phase-44",
            capabilities: [
                {
                    fix_id: "REBUILD_TRIMBOX",
                    label: "Rebuild TrimBox",
                    category: "geometry",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Automatically rebuilds corrupted page geometry.",
                    operator_message: "Restores TrimBox/MediaBox boundaries."
                },
                {
                    fix_id: "APPLY_BLEED",
                    label: "Apply Bleed Margin",
                    category: "geometry",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Adjusts the PDF bleed boxes. Visual artwork extension may still require review.",
                    operator_message: "Box expansion only; artwork is not visually extended. Review required."
                },
                {
                    fix_id: "CONVERT_CMYK",
                    label: "Convert to CMYK",
                    category: "color",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    toolchain: ["ghostscript", "pdf-lib"],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Converts colors to print-safe CMYK.",
                    operator_message: "Ghostscript CMYK conversion (requires review)."
                },
                {
                    fix_id: "STRIP_JAVASCRIPT",
                    label: "Strip JavaScript",
                    category: "security",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Removes malicious or interactive scripts.",
                    operator_message: "Strips PDF JS actions."
                },
                {
                    fix_id: "EMBED_FONTS",
                    label: "Embed Fonts",
                    category: "fonts",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    toolchain: ["ghostscript"],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Embeds missing fonts (Unsupported).",
                    operator_message: "Font embedding via Ghostscript (Unsupported)."
                },
                {
                    fix_id: "INJECT_OUTPUT_INTENT",
                    label: "Inject Output Intent",
                    category: "color",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Injects missing color profile output intent.",
                    operator_message: "Output intent profile injection."
                },
                {
                    fix_id: "FLATTEN_ANNOTATIONS",
                    label: "Flatten Annotations",
                    category: "geometry",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Removes or flattens interactive annotations.",
                    operator_message: "Removes annotation dictionaries from PDF pages (does not natively burn appearances)."
                },
                {
                    fix_id: "FLATTEN_FORMS",
                    label: "Flatten Forms",
                    category: "geometry",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Flattens interactive form fields.",
                    operator_message: "Removes AcroForm dictionaries."
                },
                {
                    fix_id: "REBUILD_XREF",
                    label: "Rebuild XREF",
                    category: "structure",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    toolchain: ["qpdf"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Repairs structural PDF corruption.",
                    operator_message: "XREF table reconstruction via QPDF."
                },
                {
                    fix_id: "FLATTEN_TRANSPARENCY",
                    label: "Flatten Transparency",
                    category: "geometry",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Flattens complex transparencies.",
                    operator_message: "Transparency flattening (Unsupported)."
                },
                {
                    fix_id: "FLATTEN_OVERPRINT",
                    label: "Flatten Overprint",
                    category: "color",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Flattens overprint effects.",
                    operator_message: "Overprint simulation (Unsupported)."
                },
                {
                    fix_id: "VALIDATE_PDFX",
                    label: "Validate PDF/X",
                    category: "compliance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Validates PDF/X compliance.",
                    operator_message: "PDF/X compliance check (Unsupported)."
                },
                {
                    fix_id: "GENERATE_PDFX",
                    label: "Generate PDF/X",
                    category: "compliance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Converts to PDF/X standard.",
                    operator_message: "PDF/X generation (Unsupported)."
                },
                {
                    fix_id: "VISUAL_BLEED_EXTENSION",
                    label: "Visual Bleed Extension",
                    category: "geometry",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Extends artwork for bleed margins visually.",
                    operator_message: "Visual bleed extension is not implemented. Current bleed handling is box adjustment only."
                },
                {
                    fix_id: "MAP_RICH_BLACK_TEXT_TO_K_ONLY",
                    label: "Map Rich Black Text to K Only",
                    category: "color",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Converts rich black text to 100% K.",
                    operator_message: "Rich black text reduction (Unsupported)."
                },
                {
                    fix_id: "MAP_REGISTRATION_COLOR_TO_BLACK",
                    label: "Map Registration Color to Black",
                    category: "color",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Maps registration color to 100% K.",
                    operator_message: "Registration color fix (Unsupported)."
                },
                {
                    fix_id: "DETECT_TOTAL_INK_COVERAGE",
                    label: "Detect Total Ink Coverage",
                    category: "color",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Detects total area coverage issues.",
                    operator_message: "TAC/TIC detection (Unsupported)."
                }
            ],
            policy_modes: [
                "SAFE",
                "REVIEW_REQUIRED",
                "EXPERIMENTAL"
            ]
        };
    }
}

module.exports = FixCapabilityContract;
