class FixCapabilityContract {
    static getCapabilities() {
        return {
            ok: true,
            version: "46.0",
            source: "SERVICE_MIRROR",
            engine_registry_compatibility: "phase-44",
            capabilities: [
                {
                    fix_id: "REBUILD_TRIMBOX",
                    label: "Rebuild TrimBox",
                    category: "geometry",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Automatically rebuilds corrupted page geometry.",
                    operator_message: "Restores TrimBox/MediaBox boundaries."
                },
                {
                    fix_id: "APPLY_BLEED",
                    label: "Apply Bleed Margin",
                    category: "geometry",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Adjusts the PDF bleed boxes. Visual artwork extension may still require review.",
                    operator_message: "Box expansion only; artwork is not visually extended. Review required."
                },
                {
                    fix_id: "CONVERT_CMYK",
                    label: "Convert to CMYK",
                    category: "color",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    toolchain: ["ghostscript", "pdf-lib"],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Converts colors to print-safe CMYK. Not production safe.",
                    operator_message: "Ghostscript CMYK conversion (requires review). Never safe."
                },
                {
                    fix_id: "STRIP_JAVASCRIPT",
                    label: "Strip JavaScript",
                    category: "pdf_security_interactivity",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    security_sensitive: true,
                    evidence_required: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Removes malicious or interactive scripts.",
                    operator_message: "Strips PDF JS actions."
                },
                {
                    fix_id: "REMOVE_LAUNCH_ACTIONS",
                    label: "Remove Launch Actions",
                    category: "pdf_security_interactivity",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    security_sensitive: true,
                    evidence_required: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Removes actions that could launch external applications or files.",
                    operator_message: "Strips PDF launch actions from catalog/page/annotation dictionaries."
                },
                {
                    fix_id: "REMOVE_EMBEDDED_FILES",
                    label: "Remove Embedded Files",
                    category: "pdf_security_interactivity",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    security_sensitive: true,
                    evidence_required: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Removes embedded files that could carry hidden or unsafe content.",
                    operator_message: "Strips embedded file streams and EmbeddedFiles name tree entries."
                },
                {
                    fix_id: "REMOVE_DOCUMENT_OPEN_ACTIONS",
                    label: "Remove Document Open Actions",
                    category: "pdf_security_interactivity",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    security_sensitive: true,
                    evidence_required: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Removes actions that automatically run when the document is opened.",
                    operator_message: "Strips catalog OpenAction / AdditionalActions entries."
                },
                {
                    fix_id: "REMOVE_PAGE_OPEN_ACTIONS",
                    label: "Remove Page Open Actions",
                    category: "pdf_security_interactivity",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    security_sensitive: true,
                    evidence_required: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Removes actions that automatically run when a page is opened.",
                    operator_message: "Strips page-level AdditionalActions (open/close) dictionaries."
                },
                {
                    fix_id: "EMBED_FONTS",
                    label: "Embed Fonts",
                    category: "fonts",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    toolchain: ["ghostscript"],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Embeds missing fonts (Review Required).",
                    operator_message: "Font embedding via Ghostscript (Review Required)."
                },
                {
                    fix_id: "OUTLINE_FONTS",
                    label: "Outline Fonts",
                    category: "fonts",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Font outlining is currently not supported.",
                    operator_message: "Font outlining is currently scaffolded."
                },
                {
                    fix_id: "REPLACE_MISSING_FONTS",
                    label: "Replace Missing Fonts",
                    category: "fonts",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Missing font replacement is currently not supported.",
                    operator_message: "Missing font replacement is currently scaffolded."
                },
                {
                    fix_id: "GLYPH_REPAIR",
                    label: "Glyph Repair",
                    category: "fonts",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Glyph repair is currently not supported.",
                    operator_message: "Glyph repair is currently scaffolded."
                },
                {
                    fix_id: "SUBSET_EMBEDDED_FONTS",
                    label: "Subset Embedded Fonts",
                    category: "font_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Subsets embedded fonts to reduce file size. Font changes require review.",
                    operator_message: "Embedded font subsetting (SKIPPED_UNSUPPORTED until safely implemented)."
                },
                {
                    fix_id: "OUTLINE_TYPE3_FONTS",
                    label: "Outline Type3 Fonts",
                    category: "font_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Converts Type3 fonts to outlines. Font changes require review.",
                    operator_message: "Type3 font outlining (SKIPPED_UNSUPPORTED until safely implemented; always review-required)."
                },
                {
                    fix_id: "REPAIR_FONT_ENCODING",
                    label: "Repair Font Encoding",
                    category: "font_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Repairs invalid font encoding. Font changes require review.",
                    operator_message: "Font encoding repair (SKIPPED_UNSUPPORTED until safely implemented; always review-required)."
                },
                {
                    fix_id: "FLAG_MISSING_GLYPHS_UNFIXABLE",
                    label: "Flag Missing Glyphs as Unfixable",
                    category: "font_governance",
                    implemented: true,
                    detectable: true,
                    autofixable: false,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Flags missing glyphs that cannot be safely repaired. Missing glyphs are not invented.",
                    operator_message: "Missing-glyph detection and flagging. Does not invent glyph data; returns REVIEW_REQUIRED evidence only."
                },
                // Phase 67: Transparency / Overprint Physical Governance
                {
                    fix_id: "FLATTEN_TRANSPARENCY",
                    label: "Flatten Transparency (Physical)",
                    category: "transparency_overprint_physical_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    rendering_safety_proven: false,
                    visual_change_expected: true,
                    toolchain: [],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Transparency flattening may affect appearance and requires review.",
                    operator_message: "Transparency flattening (physical). Always REVIEW_REQUIRED; never production-safe."
                },
                {
                    fix_id: "NORMALIZE_BLEND_MODES",
                    label: "Normalize Blend Modes",
                    category: "transparency_overprint_physical_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    rendering_safety_proven: false,
                    visual_change_expected: true,
                    toolchain: [],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Blend mode normalization may affect visual appearance and requires review.",
                    operator_message: "Blend mode normalization (physical). Always REVIEW_REQUIRED; never production-safe."
                },
                {
                    fix_id: "FLATTEN_OVERPRINT",
                    label: "Flatten Overprint (Physical)",
                    category: "transparency_overprint_physical_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    rendering_safety_proven: false,
                    visual_change_expected: true,
                    toolchain: [],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Overprint changes require visual verification.",
                    operator_message: "Overprint flattening (physical). Always REVIEW_REQUIRED; never production-safe."
                },
                {
                    fix_id: "SIMULATE_OVERPRINT_PREVIEW",
                    label: "Simulate Overprint Preview",
                    category: "transparency_overprint_physical_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    rendering_safety_proven: false,
                    visual_change_expected: true,
                    toolchain: [],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Overprint simulation preview requires visual review.",
                    operator_message: "Overprint preview simulation. Returns preview evidence only; never certifies output."
                },
                {
                    fix_id: "INJECT_OUTPUT_INTENT",
                    label: "Inject Output Intent",
                    category: "color",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    outputintent_changed: true,
                    outputintent_does_not_prove_pdfx: true,
                    pdfx_compliance_claimed: false,
                    standard_certified: false,
                    compliance_claim_allowed: false,
                    standard_claimed: null,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED"],
                    customer_message: "Injects missing color profile output intent. OutputIntent injection alone does not prove PDF/X compliance.",
                    operator_message: "Output intent profile injection. Safe only for passive metadata-only mode. OutputIntent injection alone does not prove PDF/X compliance."
                },
                {
                    fix_id: "FLATTEN_ANNOTATIONS",
                    label: "Flatten Annotations",
                    category: "pdf_security_interactivity",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    security_sensitive: true,
                    evidence_required: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Flattens interactive annotations. Requires review — appearance changes are not guaranteed to be preserved.",
                    operator_message: "Removes annotation dictionaries from PDF pages. Does not fake appearance preservation; returns SKIPPED_UNSUPPORTED/REVIEW_REQUIRED when safe flattening cannot be proven."
                },
                {
                    fix_id: "FLATTEN_FORMS",
                    label: "Flatten Forms",
                    category: "pdf_security_interactivity",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    security_sensitive: true,
                    evidence_required: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Flattens interactive form fields. Requires review — appearance changes are not guaranteed to be preserved.",
                    operator_message: "Removes AcroForm dictionaries. Does not fake appearance preservation; returns SKIPPED_UNSUPPORTED/REVIEW_REQUIRED when safe flattening cannot be proven."
                },
                {
                    fix_id: "REBUILD_XREF",
                    label: "Rebuild XREF",
                    category: "structure",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    toolchain: ["qpdf"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Repairs structural PDF corruption.",
                    operator_message: "XREF table reconstruction via QPDF."
                },
                {
                    fix_id: "NORMALIZE_OBJECT_STREAMS",
                    label: "Normalize Object Streams",
                    category: "structural_integrity",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: "conditional",
                    evidence_required: true,
                    destructive: false,
                    toolchain: ["qpdf"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Normalizes object streams for better compatibility.",
                    operator_message: "Object stream normalization."
                },
                {
                    fix_id: "FLATTEN_TRANSPARENCY",
                    label: "Flatten Transparency",
                    category: "geometry",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Flattens complex transparencies.",
                    operator_message: "Transparency flattening (Unsupported)."
                },
                {
                    fix_id: "FLATTEN_PDF",
                    label: "Flatten PDF",
                    category: "geometry",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "CRITICAL",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Broad visual rewrite to flatten PDF.",
                    operator_message: "Full PDF flattening (Unsupported)."
                },
                {
                    fix_id: "FLATTEN_OVERPRINT",
                    label: "Flatten Overprint",
                    category: "color",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Flattens overprint effects.",
                    operator_message: "Overprint simulation (Unsupported)."
                },
                {
                    fix_id: "NORMALIZE_OVERPRINT",
                    label: "Normalize Overprint",
                    category: "color",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Normalizes overprint effects.",
                    operator_message: "Overprint normalization (Unsupported)."
                },
                {
                    fix_id: "REMOVE_SOFT_MASKS",
                    label: "Remove Soft Masks",
                    category: "geometry",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Removes soft masks.",
                    operator_message: "Soft mask removal (Unsupported)."
                },
                {
                    fix_id: "RASTERIZE_TRANSPARENCY",
                    label: "Rasterize Transparency",
                    category: "geometry",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "CRITICAL",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Rasterizes transparent objects.",
                    operator_message: "Transparency rasterization (Unsupported)."
                },
                {
                    fix_id: "CONVERT_TO_PDFX_TRANSPARENCY_SAFE",
                    label: "Convert to PDF/X Transparency Safe",
                    category: "compliance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    pdfx_generation_supported: false,
                    pdfx_validation_supported: false,
                    pdfx_compliance_claimed: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "PDF/X transparency-safe conversion is not implemented or validated.",
                    operator_message: "Does not claim PDF/X compliance."
                },
                {
                    fix_id: "VALIDATE_PDFX",
                    label: "Validate PDF/X",
                    category: "compliance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    validator_required: true,
                    validator_available: false,
                    compliance_claim_allowed: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Validates PDF/X compliance.",
                    operator_message: "PDF/X compliance check (Unsupported). Must not claim PDF/X compliance without real validator."
                },
                {
                    fix_id: "VALIDATE_PDFA",
                    label: "Validate PDF/A",
                    category: "compliance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    validator_required: true,
                    validator_available: false,
                    compliance_claim_allowed: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Validates PDF/A compliance.",
                    operator_message: "PDF/A compliance check (Unsupported). Must not claim PDF/A compliance without real validator."
                },
                {
                    fix_id: "GENERATE_PDFX",
                    label: "Generate PDF/X",
                    category: "compliance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    compliance_claim_allowed: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Converts to PDF/X standard.",
                    operator_message: "PDF/X generation (Unsupported). Must not claim PDF/X."
                },
                {
                    fix_id: "CONVERT_TO_PDFX",
                    label: "Convert to PDF/X",
                    category: "compliance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    compliance_claim_allowed: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Converts to PDF/X standard.",
                    operator_message: "PDF/X generation (Unsupported). Must not claim PDF/X."
                },
                {
                    fix_id: "CONVERT_TO_PDFA",
                    label: "Convert to PDF/A",
                    category: "compliance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    compliance_claim_allowed: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Converts to PDF/A standard.",
                    operator_message: "PDF/A generation (Unsupported). Must not claim PDF/A."
                },
                {
                    fix_id: "INJECT_PDFX_OUTPUTINTENT",
                    label: "Inject PDF/X Output Intent",
                    category: "compliance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "LOW",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    outputintent_changed: true,
                    outputintent_does_not_prove_pdfx: true,
                    pdfx_compliance_claimed: false,
                    standard_certified: false,
                    compliance_claim_allowed: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Injects PDF/X OutputIntent.",
                    operator_message: "OutputIntent injection alone does not prove PDF/X compliance."
                },
                {
                    fix_id: "REPAIR_PDFX_OUTPUTINTENT",
                    label: "Repair PDF/X Output Intent",
                    category: "compliance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "LOW",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    outputintent_changed: true,
                    outputintent_does_not_prove_pdfx: true,
                    pdfx_compliance_claimed: false,
                    standard_certified: false,
                    compliance_claim_allowed: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Repairs PDF/X OutputIntent.",
                    operator_message: "OutputIntent injection alone does not prove PDF/X compliance."
                },
                {
                    fix_id: "STRIP_INVALID_PDFX_METADATA",
                    label: "Strip Invalid PDF/X Metadata",
                    category: "standards_certification",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Strips invalid PDF/X metadata.",
                    operator_message: "Must not certify anything."
                },
                {
                    fix_id: "STRIP_INVALID_PDFA_METADATA",
                    label: "Strip Invalid PDF/A Metadata",
                    category: "standards_certification",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Strips invalid PDF/A metadata.",
                    operator_message: "Must not certify anything."
                },
                {
                    fix_id: "NORMALIZE_STANDARD_METADATA",
                    label: "Normalize Standard Metadata",
                    category: "standards_certification",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Normalizes standard metadata.",
                    operator_message: "Must not certify anything."
                },
                {
                    fix_id: "MARK_STANDARD_UNCERTIFIED",
                    label: "Mark Standard Uncertified",
                    category: "compliance",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Marks artifact as standard uncertified.",
                    operator_message: "Governance action. Must never certify anything."
                },
                {
                    fix_id: "REVOKE_FALSE_CERTIFICATION",
                    label: "Revoke False Certification",
                    category: "standards_certification",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Revokes false standards certification.",
                    operator_message: "Governance action. Must never certify anything."
                },
                {
                    fix_id: "GENERATE_STANDARD_VALIDATION_REPORT",
                    label: "Generate Standard Validation Report",
                    category: "compliance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "LOW",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    validator_required: true,
                    validator_available: false,
                    compliance_claim_allowed: false,
                    standard_claimed: null,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Generates standard validation report.",
                    operator_message: "Implemented only if real validator report exists."
                },
                {
                    fix_id: "GENERATE_STANDARD_VALIDATION_REPORT_INTERNAL",
                    label: "Generate Standard Validation Report (Internal)",
                    category: "compliance",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "LOW",
                    requires_human_review: false,
                    production_safe: true,
                    destructive: false,
                    validator_required: false,
                    validator_available: false,
                    validation_performed: false,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: ["qpdf", "pdf-lib"],
                    supported_modes: ["SAFE", "REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Internal standards validation check.",
                    operator_message: "Clearly marked as internal governance report, not validator-backed report."
                },
                {
                    fix_id: "VISUAL_BLEED_EXTENSION",
                    label: "Visual Bleed Extension",
                    category: "geometry",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Extends artwork for bleed margins visually.",
                    operator_message: "Visual bleed extension is not implemented. Current bleed handling is box adjustment only."
                },
                {
                    fix_id: "MAP_RICH_BLACK_TEXT_TO_K_ONLY",
                    label: "Map Rich Black Text to K Only",
                    category: "ink_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Converts rich black text to 100% K. Ink/color changes may affect appearance and require review.",
                    operator_message: "Rich black text reduction (SKIPPED_UNSUPPORTED until safely implemented)."
                },
                {
                    fix_id: "MAP_REGISTRATION_COLOR_TO_BLACK",
                    label: "Map Registration Color to Black",
                    category: "ink_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Maps registration color to 100% K. Ink/color changes may affect appearance and require review.",
                    operator_message: "Registration color fix (SKIPPED_UNSUPPORTED until safely implemented)."
                },
                {
                    fix_id: "REDUCE_TOTAL_INK_COVERAGE",
                    label: "Reduce Total Ink Coverage",
                    category: "ink_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Reduces total ink coverage (TAC). Ink/color changes may affect appearance and require review.",
                    operator_message: "TAC reduction (SKIPPED_UNSUPPORTED until safely implemented)."
                },
                {
                    fix_id: "NORMALIZE_BLACK_TEXT",
                    label: "Normalize Black Text",
                    category: "ink_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Normalizes black text to K-only. Ink/color changes may affect appearance and require review.",
                    operator_message: "Black text normalization (SKIPPED_UNSUPPORTED until safely implemented)."
                },
                {
                    fix_id: "DETECT_SMALL_TEXT_RICH_BLACK",
                    label: "Detect Small Text Rich Black",
                    category: "ink_governance",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Detects small text rendered in rich black. Ink/color changes may affect appearance and require review.",
                    operator_message: "Small text rich-black detection (SKIPPED_UNSUPPORTED until safely implemented)."
                },
                {
                    fix_id: "NORMALIZE_ICC_PROFILE",
                    label: "Normalize ICC Profile",
                    category: "color",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Normalizes inconsistent ICC profiles.",
                    operator_message: "ICC normalization (Unsupported)."
                },
                {
                    fix_id: "REDUCE_TAC",
                    label: "Reduce Total Area Coverage",
                    category: "color",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Reduces ink coverage to safe limits.",
                    operator_message: "TAC reduction (Unsupported)."
                },
                {
                    fix_id: "DETECT_TOTAL_INK_COVERAGE",
                    label: "Detect Total Ink Coverage",
                    category: "color",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Detects total area coverage issues.",
                    operator_message: "TAC/TIC detection (Unsupported)."
                },
                {
                    fix_id: "UPSCALE_LOW_RES_IMAGES",
                    label: "Upscale Low Resolution Images",
                    category: "image",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Image upscaling is currently not supported.",
                    operator_message: "Cannot safely restore true image detail."
                },
                {
                    fix_id: "DOWNSAMPLE_EXCESSIVE_RESOLUTION",
                    label: "Downsample Excessive Resolution",
                    category: "image_quality",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Downsamples excessively high-resolution images. Selective image changes may affect appearance and require review.",
                    operator_message: "Excessive resolution downsampling (SKIPPED_UNSUPPORTED until safely implemented)."
                },
                {
                    fix_id: "CONVERT_IMAGE_RGB_TO_CMYK_SELECTIVE",
                    label: "Convert RGB Images to CMYK (Selective)",
                    category: "image_quality",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Selectively converts RGB images to CMYK. Selective image changes may affect appearance and require review.",
                    operator_message: "Selective RGB-to-CMYK image conversion (SKIPPED_UNSUPPORTED until safely implemented)."
                },
                {
                    fix_id: "TAG_UNTAGGED_IMAGES",
                    label: "Tag Untagged Images",
                    category: "image_quality",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Tags untagged images with a color profile. Selective image changes may affect appearance and require review.",
                    operator_message: "Untagged image tagging (SKIPPED_UNSUPPORTED until safely implemented)."
                },
                {
                    fix_id: "NORMALIZE_IMAGE_ICC_PROFILE",
                    label: "Normalize Image ICC Profile",
                    category: "image_quality",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: true,
                    visually_sensitive: true,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Normalizes mismatched image ICC profiles. Selective image changes may affect appearance and require review.",
                    operator_message: "Image ICC profile normalization (SKIPPED_UNSUPPORTED until safely implemented)."
                },
                {
                    fix_id: "FLAG_LOW_RES_IMAGES_UNFIXABLE",
                    label: "Flag Low Resolution Images as Unfixable",
                    category: "image_quality",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    destructive: false,
                    visually_sensitive: false,
                    evidence_required: true,
                    compliance_claim_allowed: false,
                    standard_certified: false,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Flags low-resolution images that cannot be safely improved automatically.",
                    operator_message: "Low-resolution images flagged as unfixable (no automatic upscaling performed)."
                },
                {
                    fix_id: "RECOMPRESS_IMAGES",
                    label: "Recompress Images",
                    category: "image",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Image recompression is currently not supported.",
                    operator_message: "Image recompression not production safe."
                },
                {
                    fix_id: "REPLACE_LOW_RES_IMAGES",
                    label: "Replace Low Resolution Images",
                    category: "image",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "CRITICAL",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Image replacement is currently not supported.",
                    operator_message: "Cannot replace customer assets."
                },
                {
                    fix_id: "REPAIR_JPEG_ARTIFACTS",
                    label: "Repair JPEG Artifacts",
                    category: "image",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Repairing JPEG artifacts is currently not supported.",
                    operator_message: "Cannot safely repair JPEG artifacts."
                },
                {
                    fix_id: "NORMALIZE_IMAGE_COLORSPACE",
                    label: "Normalize Image Colorspace",
                    category: "image",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Normalizing image colorspace is currently not supported.",
                    operator_message: "Image colorspace normalization not production safe."
                },
                {
                    fix_id: "REMOVE_IMAGE_ALPHA",
                    label: "Remove Image Alpha Channel",
                    category: "image",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Removing image alpha channel is currently not supported.",
                    operator_message: "Alpha removal not production safe."
                },
                {
                    fix_id: "REPAIR_DAMAGED_IMAGE_OBJECT",
                    label: "Repair Damaged Image Object",
                    category: "image",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "CRITICAL",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Repairing damaged image objects is currently not supported.",
                    operator_message: "Cannot repair corrupted image streams safely."
                },
                {
                    fix_id: "VECTORIZE_BITMAP_TEXT",
                    label: "Vectorize Bitmap Text",
                    category: "image",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "CRITICAL",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Vectorizing bitmap text is currently not supported.",
                    operator_message: "Cannot vectorize bitmap text as production-safe."
                },
                {
                    fix_id: "RESTORE_RASTERIZED_VECTOR",
                    label: "Restore Rasterized Vector",
                    category: "image",
                    implemented: false,
                    detectable: true,
                    autofixable: false,
                    risk_level: "CRITICAL",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    toolchain: [],
                    supported_modes: ["EXPERIMENTAL"],
                    customer_message: "Restoring rasterized vectors is currently not supported.",
                    operator_message: "Cannot safely restore vectors from raster images."
                },
                {
                    fix_id: "ADD_CROP_MARKS",
                    label: "Add Crop Marks",
                    category: "page_marks",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: false,
                    evidence_required: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Adds crop marks for printing. Review required to ensure marks do not obscure important content.",
                    operator_message: "Adds TrimBox visual marks. Requires human review. Not production safe by default."
                },
                {
                    fix_id: "REMOVE_REGISTRATION_MARKS",
                    label: "Remove Registration Marks",
                    category: "page_marks",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "HIGH",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: true,
                    evidence_required: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Removes registration marks. Requires human review.",
                    operator_message: "Removes mark objects outside TrimBox. Requires human review and safety checks. Destructive."
                },
                {
                    fix_id: "NORMALIZE_PAGE_MARKS",
                    label: "Normalize Page Marks",
                    category: "page_marks",
                    implemented: true,
                    detectable: true,
                    autofixable: true,
                    risk_level: "MEDIUM",
                    requires_human_review: true,
                    production_safe: false,
                    visually_sensitive: true,
                    destructive: false,
                    evidence_required: true,
                    toolchain: ["pdf-lib"],
                    supported_modes: ["REVIEW_REQUIRED", "EXPERIMENTAL"],
                    customer_message: "Normalizes existing page marks. Review required.",
                    operator_message: "Adjusts registration colors to true separation. Requires human review."
                }
            ],
            policy_modes: [
                "SAFE",
                "REVIEW_REQUIRED",
                "EXPERIMENTAL"
            ]
        };
    }
}

module.exports = FixCapabilityContract;
